import { Component, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-insights',
  imports: [CommonModule],
  templateUrl: './insights.component.html',
  styleUrl: './insights.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class InsightsComponent {
  
  downloadReport(): void {
    // Create a comprehensive report
    const reportContent = this.generateReport();
    const blob = new Blob([reportContent], { type: 'text/markdown' });
    const url = window.URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.download = 'london-housing-market-insights-2a-report.md';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  }

  contactExperts(): void {
    // Open email client or redirect to contact form
    const email = 'contact@2amarketintelligence.com';
    const subject = encodeURIComponent('London Housing Market Consultation Request');
    const body = encodeURIComponent(
      `Dear 2A team,

I would like to schedule a consultation regarding London's housing market insights and strategic solutions.

Please let me know your availability for a discussion.

Best regards`
    );
    
    window.location.href = `mailto:${email}?subject=${subject}&body=${body}`;
  }

  private generateReport(): string {
    return `# London Housing Market Insights Report - 2A Avenue Analytics

## Executive Summary

This comprehensive analysis examines London's housing affordability crisis and presents strategic solutions for stakeholders. The market faces unprecedented challenges with price-to-income ratios reaching 12.5x, making London one of the world's least affordable housing markets.

## Key Market Challenges

### 1. Short-term Rentals Impact
- **Active Listings**: 51,611 (28% annual growth)
- **Occupancy Rate**: 63%
- **Average Daily Rate**: £222
- **Annual Revenue per Property**: £50,602

The "Airbnb Effect" has significantly reduced long-term housing supply, creating artificial scarcity and driving up prices.

### 2. Price-to-Income Gap
- **Current Ratio**: 12.5x
- **Average Property Price**: £525,000
- **Average Annual Income**: £42,000
- **Annual Price Growth**: 15%

Property prices have outpaced wage growth by more than a factor of ten over the past decade.

### 3. Supply & Demand Imbalance
- **Affected Residents**: 2M+
- **Boroughs Impacted**: All 33 London boroughs
- **Housing Shortfall**: Estimated 100,000 units annually

Population growth combined with limited new construction has created severe housing shortages.

## Strategic Solutions Framework

### High Impact Solutions (5-10 years)

#### Increase Housing Supply
- **Zone Reform**: Implement higher density development allowances
- **Commercial Conversion**: Incentivize office-to-residential conversions
- **Transport-Linked Development**: Focus on housing near transport hubs

#### Regulatory Reform
- **Licensing Requirements**: Implement short-term rental licensing
- **90-Day Rental Caps**: Limit annual short-term rental days
- **Primary Residence Verification**: Ensure owner-occupancy requirements

### Medium Impact Solutions (1-7 years)

#### Financial Innovation
- **Shared Equity Schemes**: Government-private partnership models
- **First-Time Buyer Accounts**: Tax-advantaged savings vehicles
- **Employer-Assisted Programs**: Workplace housing benefits

#### Community-Led Initiatives
- **Community Land Trusts**: Non-profit housing development
- **Co-operative Models**: Resident-owned housing cooperatives
- **Local Partnerships**: Borough-specific development programs

## Investment Requirements

**Total Investment Needed**: £500 billion by 2030
**Annual Housing Target**: 100,000 new homes
**Implementation Timeline**: 2024-2030

## Recommendations

1. **Immediate Action** (2024-2025):
   - Implement short-term rental regulations
   - Accelerate planning permission processes
   - Launch first-time buyer assistance programs

2. **Medium-term Strategy** (2025-2028):
   - Scale up housing construction
   - Develop financial innovation products
   - Expand community-led initiatives

3. **Long-term Vision** (2028-2030):
   - Achieve housing market balance
   - Establish sustainable affordability models
   - Create resilient housing ecosystem

## Conclusion

London's housing affordability crisis requires coordinated, multi-faceted action. Through strategic implementation of the proposed solutions, the city can work toward a future where everyone has access to safe, affordable housing.

---
*Report generated by Avenue Analytics - London Housing Market Analysis*
*Date: ${new Date().toLocaleDateString('en-GB')}*
*Contact: contact@2amarketintelligence.com*
`;
  }
}
